Repository RedHatInsights/ros-backend, pull requests merged in 2023-10, with the labels that each got.

#375 RHIROS-531 ROS BE Sequence and DB schema diagram
  README.md
  docs/db_schema.puml
  docs/ros_sequence.puml
Labels: Waiting on contributor

#339 Fixes #RHIROS-1231, #RHIROS-1172, #RHIROS-1175, #RHIROS-1177 - store suggested instance type info and api changes
  migrations/versions/93262eab7d77_update_top_candidate_and_top_candidate_price_for_existing_records.py
  migrations/versions/c6f2cd708cea_add_top_candidate_top_candidate_price_.py
  ros/api/common/instance_types_helper.py
  ros/api/common/utils.py
  ros/api/routes.py
  ros/api/v1/hosts.py
  ros/api/v1/suggested_instance_types.py
  ros/lib/models.py
  ros/lib/utils.py
  ros/openapi/openapi.json
  ros/processor/insights_engine_consumer.py
  tests/fixtures/db_fixtures.py
  tests/test_api_endpoints.py
Labels: waiting for QE

#378 add constants in one file
  ros/api/modules/recommendations.py
  ros/api/v1/hosts.py
  ros/lib/config.py
  ros/lib/constants.py
  ros/processor/event_producer.py
  ros/processor/insights_engine_consumer.py
  tests/test_insights_engine_result_consumer.py
Labels: ready for review

#383 Refs #RHIROS-1231 - don't add double quotes to top_candidate values
  migrations/versions/93262eab7d77_update_top_candidate_and_top_candidate_price_for_existing_records.py
  ros/api/common/instance_types_helper.py
  ros/api/v1/suggested_instance_types.py
Labels: ready for review

#381 Fixes #RHIROS-1357 - Upgrade to Python 3.11
  .github/workflows/build.yml
  .github/workflows/build_with_latest_direct_deps.yml
  .github/workflows/build_with_latest_indirect_deps.yml
  Dockerfile
  poetry.lock
  pyproject.toml
Labels: ready for merge
